### ISSUE TITLE
TypeError: mParallel._print() missing 1 required positional argument: 'msg_args'

### ISSUE THREAD

**Issue by juanmafdez** [rramosp/geetiles#25]
# Traceback
Traceback (most recent call last):
  File "/usr/local/bin/geet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/geetiles/main.py", line 95, in main
    make_grid(aoi_wkt_file     = args.aoi_wkt_file, 
  File "/usr/local/lib/python3.10/dist-packages/geetiles/cmds.py", line 203, in make_grid
    grid = build_grid(aoi=aoi, chip_size_meters=chip_size_meters)
  File "/usr/local/lib/python3.10/dist-packages/geetiles/cmds.py", line 268, in build_grid
    parts = utils.mParallel(n_jobs=-1, verbose=30)(delayed(get_polygon)(m, gx, gy, minx, miny) \
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 1961, in __call__
    self._print(
TypeError: mParallel._print() missing 1 required positional argument: 'msg_args'

# Enviroment
On a clean Google Colab enviroment. Installed with: ! pip install geetiles

# Proposed fix
## Fix 1
Code modification in utils.py, line 124:
### Current code
class mParallel(Parallel):
    """
    substitutes joblib.Parallel with richer verbose progress information
    """
    def _print(self, msg, msg_args):
        if self.verbose > 10:
            fmsg = '[%s]: %s' % (self, msg % msg_args)
            sys.stdout.write('\r ' + fmsg)
            sys.stdout.flush()
### Proposal
class mParallel(Parallel):
    """
    substitutes joblib.Parallel with richer verbose progress information
    """
    def _print(self, msg):
        if self.verbose > 10:
            fmsg = '[%s]: %s' % (self, msg)
            sys.stdout.write('\r ' + fmsg)
            sys.stdout.flush()
## Fix 2 (for user)
Uninstall current version for joblib and install a previous version, example joblib 1.2.0

**Comment by rramosp** [comment]
thank you juanma for signalling this ... I think we already fixed this
