### ISSUE TITLE
Authentication workflow deprecated - now requires google cloud project

### ISSUE THREAD

**Issue by b-d-e** [rramosp/geetiles#26]
Per https://developers.google.com/earth-engine/guides/transition_to_cloud_projects

**Comment by rramosp** [comment]
thanks b-d-e !!!!! will work soon on this

**Comment by b-d-e** [comment]
No worries @rramosp! If it helps, I made PR #27 which contains a fix that worked for me. 

Though you might have a different way you want to solve it - no worries if so.

**Comment by rramosp** [comment]
oh! thanks so much, will definitely look into it!!

**Comment by rramosp** [comment]
merged!!! thanks for your effort!! it was really cool!

**Comment by b-d-e** [comment]
no worries at all, glad it is useful

**Comment by rramosp** [comment]
included in release 0.1.7
